#!/usr/bin/env bash
#
# Render the Homebrew formula for a release tag and push it to the tap repos.
# Replaces GoReleaser's deprecated `brews` publisher.
#
# Publishes to two taps:
#   - sorokin-vladimir/homebrew-tap   canonical
#   - sorokin-vladimir/homebrew-tele  deprecated, marked with `deprecate!`
#
# Tarball checksums are read from dist/checksums.txt (produced by
# `goreleaser release`), so this MUST run after goreleaser in the same job.
#
# Usage: scripts/update-formula.sh <tag>
# Requires: HOMEBREW_TAP_TOKEN in the environment (push access to both taps).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

tag=${1:?usage: scripts/update-formula.sh <tag>}
version=${tag#v}
: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN is not set}"

owner="sorokin-vladimir"
base="https://github.com/${owner}/tele/releases/download/${tag}"
checksums="dist/checksums.txt"

# Date the legacy tap was deprecated. Kept constant so re-releases don't
# reset it; `deprecate!` uses it to decide when to start warning users.
deprecated_since="2026-06-19"

# sha256 for a release artifact, looked up by file name in checksums.txt.
sha() {
  local name=$1 line
  line=$(grep -E "  ${name}\$" "$checksums") \
    || { echo "checksum for $name not found in $checksums" >&2; exit 1; }
  echo "${line%% *}"
}

darwin_amd64=$(sha tele_darwin_amd64.tar.gz)
darwin_arm64=$(sha tele_darwin_arm64.tar.gz)
linux_amd64=$(sha tele_linux_amd64.tar.gz)
linux_arm64=$(sha tele_linux_arm64.tar.gz)

# Render Formula/tele.rb. $1 is an extra, already-indented Ruby line injected
# into the class body (used for `deprecate!` on the legacy tap); pass "" for none.
render_formula() {
  cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class Tele < Formula
  desc "TUI Telegram client"
  homepage "https://github.com/${owner}/tele"
  version "${version}"
${1}
  on_macos do
    if Hardware::CPU.intel?
      url "${base}/tele_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
    if Hardware::CPU.arm?
      url "${base}/tele_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${base}/tele_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${base}/tele_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
  end

  def install
    bin.install "tele"
  end

  test do
    system "#{bin}/tele", "--version"
  end
end
RB
}

# Clone a tap, write the formula, and push only if it changed.
publish() {
  local repo=$1 formula=$2 workdir
  workdir=$(mktemp -d)
  git clone --depth 1 \
    "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${owner}/${repo}.git" \
    "$workdir"

  mkdir -p "$workdir/Formula"
  printf '%s' "$formula" > "$workdir/Formula/tele.rb"

  git -C "$workdir" config user.name "github-actions[bot]"
  git -C "$workdir" config user.email "github-actions[bot]@users.noreply.github.com"

  if git -C "$workdir" diff --quiet; then
    echo "${repo}: formula already up to date for ${tag}"
  else
    git -C "$workdir" add Formula/tele.rb
    git -C "$workdir" commit -m "Brew formula update for tele version ${tag}"
    git -C "$workdir" push
    echo "${repo}: pushed formula for ${tag}"
  fi
  rm -rf "$workdir"
}

deprecate="  deprecate! date: \"${deprecated_since}\", because: \"this tap is deprecated; migrate to sorokin-vladimir/tap\""

publish homebrew-tap  "$(render_formula "")"
publish homebrew-tele "$(render_formula "$deprecate")"
